version: '3'

services:
  storage-monitor:
    build: 
      dockerfile: Dockerfile.local
    container_name: raspberry-pi-storage-monitor
    ports:
      - "5000:5000"
    volumes:
      - /:/host-root:ro
    restart: always
    # System restart policies
